### ISSUE TITLE
Validation failures after initial validation success is never getting fixed as puppet will not run there

### ISSUE THREAD

**Issue by hkumarmk** [JioCloud/puppet-rjil#214]
We had seen below incident.

System had been build and timed out, but two compute nodes had validation failures.

When I checked those systems, I see that nova-compute were not running there. Here are the things happend there.

1. puppet configured nova-compute  and started it
2. Validation checks run by maybe_upgrade and declared the system passed validation and thus stopped any further puppet execution
3. Because of an initial failure (some issue with 0mq) nova-compute dead after few seconds ( 1-2 mins) - it just initialized and then went down as it crashed because of RPC errors (This may be because of any initial connection failures or something, which may need further investigation).
4. Because of the validation succeed, maybe_upgrade never run puppet and thus it never got fixed
5. I logged into those machines and run puppet manually once, which fixed that issue.
6. After that, no validation failures there.

The problem here was that we are only running puppet in case of initial deployment and if there is any upgrades. 

I suggest that we should run puppet on any vaildation failures (also health check failures) so that those failures can be handled automatically by puppet without a user intervention.

**Comment by bodepd** [comment]
this was definitely fixed by #137
