### ISSUE TITLE
Vagrant Up failes, Unable to find /vagrant/hiera/hiera.yaml

### ISSUE THREAD

**Issue by saneax** [JioCloud/puppet-rjil#310]
inside the guest VM, the below fails
 54       # This seems wrong - Soren
 55       config.vm.provision 'shell', :inline =>
 56          'cp /vagrant/hiera/hiera.yaml /etc/puppet'

we have to change to 
 54       # This seems wrong - Soren
 55       config.vm.provision 'shell', :inline =>
 56          'cp /etc/puppet/manifests/hiera/hiera.yaml /etc/puppet'

/vagrant is unavailable, I am assuming, since we are using synced_folders, it disables the default mount /vagrant.

**Comment by saneax** [comment]
==> etcd1: Running provisioner: shell...
    etcd1: Running: inline script
==> etcd1: stdin: is not a tty
==> etcd1: cp: 
==> etcd1: cannot stat ‘/vagrant/hiera/hiera.yaml’
==> etcd1: : No such file or directory

**Comment by hkumarmk** [comment]
I dont believe this is true, we never faced this issue, and I still have vagrant which is mounted.

**Comment by saneax** [comment]
I am facing this issue, I am using the following versions of vagrant and
virtualbox, and if I change the path to /etc/puppet/manifests/hiera/hiera.yaml
it works. I can work around it by just changing my copy.

In which case feel free to close this issue.


On Wed, Jan 14, 2015 at 6:23 PM, Harish Kumar <notifications@github.com>
wrote:

> I dont believe this is true, we never faced this issue, and I still have
> vagrant which is mounted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/puppet-rjil/issues/310#issuecomment-69911793>
> .
>



-- 
Sanjay Upadhyay
http://saneax.blogspot.com

**Comment by bodepd** [comment]
resolved by #312
