### ISSUE TITLE
Skipping tempest tests not currently valid in our environment

### ISSUE THREAD

**Issue by pandeyop** [JioCloud/puppet-rjil#311]
We can skip tests which aren't currently relevant for our environment through the below negative lookahead regex:

./run_tempest.sh -N 'tempest\.*(?!(.*thirdparty)|(.*baremetal)|(.*data_processing)|(.*messaging)|(.*orchestration)|(.*vpnaas)|(.*test_metering)|(.*cli)|(.*test_load_balancer)|(.*fwaas))'

**Comment by sorenh** [comment]
Please submit a patch for this. The script that runs tempest is build_scripts/test.sh.

**Comment by pandeyop** [comment]
Sure. I would be submitting a patch for this today.

**Comment by pandeyop** [comment]
The patch for this has been submitted:
https://github.com/JioCloud/puppet-rjil/pull/315

**Comment by pandeyop** [comment]
Closing this issue as the PR #315 has been merged.
