### ISSUE TITLE
sometimes consul server joining to different datacenter

### ISSUE THREAD

**Issue by hkumarmk** [JioCloud/puppet-rjil#632]
I see sometimes consul server joining to different datacenter, because of which the entire at/gate are failing (especially when it happen on bootstrap1)

hkumar@bootstrap1-testjenkins-puppet-rjil-gate-1368:~$ host keystone
Host keystone.node.consul not found: 2(SERVFAIL)

hkumar@bootstrap1-testjenkins-puppet-rjil-gate-1368:~$ sudo tail -f /var/log/upstart/consul.log 
    2015/06/08 06:22:44 [INFO] serf: EventMemberJoin: cp2-testjenkins-puppet-rjil-gate-1368 10.0.0.28
    2015/06/08 06:22:44 [INFO] serf: EventMemberJoin: oc1-test3807 10.0.0.115
    2015/06/08 06:22:44 [INFO] consul: adding server oc1-test3807 (Addr: 10.0.0.115:8300) (DC: 0cf828487fec4e8fb148f87374fc1d9f)
    2015/06/08 06:22:44 [INFO] serf: EventMemberJoin: stmonleader1-testjenkins-puppet-rjil-gate-1365 10.0.0.43
    2015/06/08 06:22:44 [INFO] serf: EventMemberJoin: ocdb1-testjenkins-puppet-rjil-gate-1366 10.0.0.76
    2015/06/08 06:22:44 [INFO] consul: adding server ocdb1-testjenkins-puppet-rjil-gate-1366 (Addr: 10.0.0.76:8300) (DC: 163188b4ba0e473796c954e09f1d624f)
    2015/06/08 06:22:44 [INFO] serf: EventMemberJoin: stmon1-testdan-kilo-test290515210415 10.0.0.36
    2015/06/08 06:22:44 [INFO] serf: Re-joined to previously known node: stmonleader1-testjenkins-puppet-rjil-gate-1302: 10.0.0.52:8301
    2015/06/08 06:22:44 [ERR] agent: failed to sync remote state: No cluster leader
==> Newer Consul version available: 0.5.2
    2015/06/08 06:23:02 [INFO] agent: Synced check 'puppet'
    2015/06/08 06:23:02 [INFO] agent: Synced check 'validation'
    2015/06/08 06:23:02 [INFO] agent: Synced check 'validation'
    2015/06/08 06:24:58 [INFO] consul: New leader elected: ocdb1-testdan-kilo-test290515210415
    2015/06/08 06:27:54 [INFO] agent: Synced check 'service:ssh'
    2015/06/08 06:32:24 [INFO] serf: EventMemberFailed: ocdb1-testjenkins-puppet-rjil-gate-1372 10.0.0.89
    2015/06/08 06:32:54 [INFO] agent: Synced check 'service:ssh'

**Comment by hkumarmk** [comment]
I have seen multiple gate failures because of this issue.

**Comment by bodepd** [comment]
this can always be fixed by deleting all builds, and rebuilding everything from scratch.

**Comment by anshprat** [comment]
resolved via https://github.com/JioCloud/puppet-rjil/pull/711
