### ISSUE TITLE
some builds are failing because of ntpdate doesnt work on bootstrap1

### ISSUE THREAD

**Issue by hkumarmk** [JioCloud/puppet-rjil#663]
It seems ntpdate to pool.ntp.org is not working sometimes which is causing the build failures. 

I see a solution to run ntpdate on all but bootstrap1 which is the local ntp server for the build or may be we could sync the time with any other internal node (may be httpproxy node?).

**Comment by bodepd** [comment]
what changed that is causing this, what was the symptom? I haven't been seeing this.

**Comment by hkumarmk** [comment]
I have seen at least 3 times from yesterday and today in different builds - 2 in undercloud builds and one on gates - the symptom is ntpdate (to pool.ntp.org) just dont work on bootstrap and thus ntp.service.consul never get registered in consul which is causing build failures.

**Comment by anshprat** [comment]
resolved via PR, closing.
